### ISSUE TITLE
very cool repo but question,

### ISSUE THREAD

**Issue by KiExitDispatcher** [AdvDebug/BehavEye#2]
will you add something, monitor data coming to and out of your machine, it would be pretty useful.

**Comment by AdvDebug** [comment]
sorry but i don't understand what you mean, do you mean monitoring the whole system network data?

**Comment by KiExitDispatcher** [comment]
yeah in nutshell something like that, english isnt my friend so i have hard time explaining.

**Comment by AdvDebug** [comment]
sorry but this project is specifically designed for a single-process monitoring.

**Comment by KiExitDispatcher** [comment]
aight, ty.
